#!./tbenv/bin/python
import sys

from bot_runner import BotRunner
import settings
from talkbackbot import TalkBackBotFactory


if __name__ == '__main__':
    command = ""
    try:
        command = sys.argv[1]
    except IndexError:
        print "No command specified, try start or stop"
        exit(1)
    runner = BotRunner(settings.PID_FILE, TalkBackBotFactory)
    try:
        method = getattr(runner, command)
        method()
    except AttributeError:
        print "Unknown command '%s'; try start or stop" % (command)