#!./bin/python

import os
import signal
import sys
from bot import WSRSDaemon

class BotRunner(object):

    PID_FILE = "./wsrs.pid"

    def start(self):
        bot = WSRSDaemon(self.PID_FILE)
        bot.start()

    def stop(self):
        try:
            pid_file = open(self.PID_FILE)
        except IOError:
            print "pid file '%s' not found; perhaps the process is not running"\
                % (self.PID_FILE)
            return
        pid = pid_file.read()
        pid_file.close()
        os.kill(int(pid), signal.SIGHUP)
        os.remove(self.PID_FILE)

if __name__ == '__main__':
    command = sys.argv[1]
    runner = BotRunner()
    try:
        method = getattr(runner, command)
        method()
    except AttributeError:
        print "Unknown command '%s'; try start or stop" % (command)